name: "Validate Renovate configuration"
on:
  push:
    paths:
      - "renovate.json"
      - .github/workflows/renovate-config-validator.yml
  pull_request:
    paths:
      - "renovate.json"
      - .github/workflows/renovate-config-validator.yml
permissions:
  contents: read
jobs:
  validate-config:
    uses: deliveroo/renovate-runner/.github/workflows/reusable-config-validator.yml@main
