name: Reset Staging
on:
  schedule:
    - cron: '0 3 * * 1'
  workflow_dispatch:
jobs:
  reset-staging:
    runs-on: ubuntu-latest
    container: deliveroo/git-staging:1.3.0
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set the current directory as a safe directory
        run: git config --global --add safe.directory $(realpath .)
      - name: Reset staging branch to master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git-staging -update
      - name: Force push staging
        run: git push --force origin staging
